# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(976, 595)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 470, 951, 27))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openImgBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openImgBtn.setObjectName("openImgBtn")
        self.horizontalLayout.addWidget(self.openImgBtn)
        self.preImgBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.preImgBtn.setObjectName("preImgBtn")
        self.horizontalLayout.addWidget(self.preImgBtn)
        self.nextImgBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nextImgBtn.setObjectName("nextImgBtn")
        self.horizontalLayout.addWidget(self.nextImgBtn)
        self.saveBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(780, 40, 171, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.resList = QtWidgets.QListView(self.verticalLayoutWidget_3)
        self.resList.setObjectName("resList")
        self.verticalLayout_3.addWidget(self.resList)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 40, 581, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(780, 10, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(770, 410, 21, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(840, 410, 21, 17))
        self.label_4.setObjectName("label_4")
        self.x_coord = QtWidgets.QLabel(Form)
        self.x_coord.setGeometry(QtCore.QRect(800, 410, 31, 17))
        self.x_coord.setObjectName("x_coord")
        self.y_coord = QtWidgets.QLabel(Form)
        self.y_coord.setGeometry(QtCore.QRect(870, 410, 31, 17))
        self.y_coord.setObjectName("y_coord")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 160, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 156, 197))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listView = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.listView.setGeometry(QtCore.QRect(0, 0, 161, 201))
        self.listView.setObjectName("listView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.openImgBtn.setText(_translate("Form", "Open"))
        self.preImgBtn.setText(_translate("Form", "Pre"))
        self.nextImgBtn.setText(_translate("Form", "Next"))
        self.saveBtn.setText(_translate("Form", "Save"))
        self.label.setText(_translate("Form", "Result:"))
        self.label_2.setText(_translate("Form", "Image:"))
        self.label_3.setText(_translate("Form", "X:"))
        self.label_4.setText(_translate("Form", "Y:"))
        self.x_coord.setText(_translate("Form", "0"))
        self.y_coord.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "Keypoint List:"))

